---
title: "Aulas ministradas"
lang: "pt-BR"
format:
  html
---

<!-- ::: {#hero-heading} -->
Este documento apresenta a organização inicial das aulas do curso de R e RStudio.\
O objetivo é guiar os estudantes desde a instalação dos programas até o uso prático de scripts, diretórios de trabalho, painéis do RStudio e os principais tipos de variáveis.

As aulas foram estruturadas de forma progressiva, para que cada etapa sirva de base para a seguinte.

```{r}
#| echo: false
#| message: false
#| warning: false

# Carregar pacotes necessários
library(readxl)
library(dplyr)
library(kableExtra)
library(lubridate)
library(hms)
library(stringr)


aulas_ministradas <- read_excel("banco_dados/aulas_ministradas.xlsx", 
    sheet = "Plan1")

```


```{r}
#| echo: false
# Mostrar tabela estilizada no estilo do site
aulas_ministradas |>
  mutate(
    Data = format(Data, "%d/%b/%Y", locale = "pt_BR.UTF-8"),
    `Horário de nício da aula` = format(`Horário de nício da aula`, "%H:%M"),
    `Horário de fim da aula`    = format(`Horário de fim da aula`, "%H:%M"),
    `Número de horas` = round(`Número de horas`,2)
  ) |> 
  kable(
    caption = "Aulas ministradas no Curso de Estatística com R para Experimentação Agrícola.",
    format = "html",
    table.attr = "class='styled-table'"
  ) |> 
  kable_styling(
    html_font = "Arial",
    full_width = TRUE,
    position = "center"
    )

```

