---
title: "Central de Ferramentas"
format: html
execute: 
  echo: false
---


Explore ferramentas práticas e interativas criadas para facilitar sua vida acadêmica e profissional.  

Comece testando abaixo:


::: {#hero-banner}

<h1> <i class="fas fa-chart-line"></i> Gerar Regressão Linear</h1>
<p>
Esta ferramenta permite gerar gráficos de regressão linear simples a partir de dados X e Y, exibindo a equação da reta e o coeficiente de determinação (R²). É ideal para verificar o ajuste de curvas, sendo especialmente útil em laboratórios durante a construção de curvas de soluções em análises.
</p>

[**ACESSAR**](https://solutionsapp.shinyapps.io/regressaosimples/){.app-btn target="_blank"}

:::


::: {#hero-banner}

<h1> <i class="fas fa-leaf"></i> Agrofit</h1>
<p>
Aplicativo para consulta e análise de dados do Agrofit. Permite acessar informações de produtos, culturas e registros de forma prática.
</p>

[**ACESSAR**](https://marlenildo.site/agrofit){.app-btn target="_blank"}

:::


::: {#hero-banner}

<h1> <i class="fas fa-balance-scale"></i> Digitar Pesos</h1>
<p>
Aplicativo para registro e organização de dados de pesagem de amostras. Facilita a digitação, reduz erros e gera arquivos organizados para análise posterior.
</p>

[**ACESSAR**](https://marlenildo.site/digitar_pesos){.app-btn target="_blank"}

:::
